### ISSUE TITLE
Unable to cache instance if model's schema does not have id field

### ISSUE THREAD

**Issue by c10h22** [DanielHreben/sequelize-transparent-cache#2]
Hello,

I noticed that cache's keys are formed from an array of model name and instance id : 
`const key = [
    getInstanceModel(instance).name,
    instance.id
  ]
`
If we already have an id field in our model like :
`const user = await User.cache().create({
    id: 1,
    name: 'Daniel'
  })
`
 it works as expected as in our cache we will have an entry with key "models:user:1" (supposing our namespace is models)

but imagine this case:

`const user = await User.cache().create({
    email: 'daniel@google.com',
    name: 'Daniel'
  })
`

this leads to an entry in cache with key "models:user:" as lib expect to have field "id"

**Comment by DanielHreben** [comment]
Deployed v1.1.2 to npm. Thanks for participation!
