### ISSUE TITLE
Sequelize v4.41.0 deprecation of findById

### ISSUE THREAD

**Issue by andreisocaciu** [DanielHreben/sequelize-transparent-cache#22]
This sequelize release deprecated the `findById` method and I thought you should know, and maybe update the API to include the new `findByPk` method to the cache object.

**Comment by DanielHreben** [comment]
Thanks! I will prepare new release with according changes soon.

**Comment by DanielHreben** [comment]
Done in [v1.2.5](https://github.com/DanielHreben/sequelize-transparent-cache/commit/47fade83a142dde6c72158e7aa02c80714d3dc48)
