### ISSUE TITLE
Question: Why allow reads out of cache?

### ISSUE THREAD

**Issue by DaveStein** [DanielHreben/sequelize-transparent-cache#31]
Been looking into the niche world of "open source projects that tie together redis abstractions over mysql abstractions." I'm using `redis` and `sequelize` now, although changing to `ioredis` wouldn't be a big deal. Came across your library and like that it uses composition and has writes baked in. 

In order to use yours, I'd need to submit a PR to support static `destroy`, but that's not too bad (probably win/win). I can delete a user, and thus would need to delete all individual entries of a "entity" for a user.

So I was wondering why `user.cache().update` was done rather than hijacking `user.update` in some way. My concern is that it would be too easy for new devs on a project to accidentally write `user.update` instead of `user.cache().update` and let that slip through.

**Comment by DanielHreben** [comment]
Hi @DaveStein ! 
I see few reasons here:
- explicit is better than implicit: that way ist's easier to anyone to see what exactly this call does once found in code
- simplicity: hijacking update is more complicated and could conflict with other libraries or user's code 
- extensibility: in the future this lib will support different type of cache that could not be automatically invalidated\updated, and current approach is pretty consistent in terms of api with this future feature, see #29

**Comment by DaveStein** [comment]
And you're against extending classes I imagine? I know all the arguments for composition over extending :) The code below shows what I'm currently doing, that I would swap out for your repo. I basically take any model I want to use cache on and have it extend this instead of `Sequelize.Model` directly. 

In terms of ticket #29, I'd imagine cache keys can be set by serializing options like `where` & `order` together - or allowing folks to define the cache key on certain calls. I think things like `findAll` can automatically be invalidated similarly to what I did below. Even if you are doing `User.cache().findAll` you'd still have access to `User` which can have a method that returns an array of methods to run when doing updates/destroys. ie a bulk equivalent to `getCacheKey`. I'll comment more on 29 itself though.

```
export default class CacheModel extends Sequelize.Model {
  /**
   * Returns the number of seconds cache should stay saved
   *
   * @returns {Number}
   */
  static getCacheTtl() {
    return this.constructor.getCacheTtl ? this.constructor.getCacheTtl() : SECONDS_IN_DAY;
  }

  /**
   * Returns the number of seconds cache should stay saved
   *
   * @returns {Number}
   */
  getCacheTtl() {
    return this.constructor.getCacheTtl ? this.constructor.getCacheTtl() : SECONDS_IN_DAY;
  }

  /**
   * Returns from cache, if existing. Otherwise, hits DB
   *
   * @param {Number} id
   * @returns {Promise<Sequelize.Model>}
   */
  static async findById(id) {
    const cacheKey = this.getCacheKey(id);
    const cacheValue = await redis.get(cacheKey);

    if (cacheValue) {
      log(`> Cache hit for ${cacheKey}`);
      const options = {
        isNewRecord: false
      };
      const values = JSON.parse(cacheValue);
      return new this(values, options);
    }

    const entity = await super.findById(...arguments);

    if (!entity) {
      return entity;
    }

    const value = JSON.stringify(entity.get());
    const ttl = this.getCacheTtl();
    log(`> Setting cache for ${cacheKey} for ${ttl} as ${value}`);
    await redis.set(cacheKey, value, 'EX', ttl);

    return entity;
  }

  /**
   * @throws CacheModelError
   */
  static async update() {
    throw new CacheModelError('Not implemented for cache busting yet');
  }

  /**
   * Destroyed multiple entries and clears their cache keys
   *
   * @param {Object} injections
   * @param {Array} injections.entities - array of Sequelize.Models
   * @param {Object} options
   *
   * @returns {Number} rows destroyed
   */
  static async destroy(injections, options) {
    // If there was need for pre destroy work, entities would have been selected already
    let entities = injections.entities;

    /**
     * If there was no pre destroy work, entities must be found to get their IDs
     * This must be done before destroy so IDs can be calculated for cache keys
     */
    if (!entities) {
      entities = this.findAll(options);
    }

    if (!entities) {
      return 0;
    }

    const destroyed = await super.destroy(options);

    const entityIds = entities.map(e => e.get('id'));
    const keyDeletions = entityIds.map(entityId => {
      const cacheKey = this.getCacheKey(entityId);

      log(`> Deleting cache key ${cacheKey}`);

      return redis.del(cacheKey);
    });

    await Promise.all(keyDeletions);

    // Sanity check
    if (destroyed !== entities.length) {
      throw new CacheModelError('Did not destroy expected amount', {
        entities: entities.length,
        destroyed,
        options
      });
    }

    return destroyed;
  }

  /**
   * Destroys object and cache key
   *
   * @param {Object} options
   *
   * @returns {Number}
   */
  async destroy(options) {
    const cacheKey = this.constructor.getCacheKey(this.get('id'));

    const destroyed = await super.destroy(options);
    log(`> Deleting cache key ${cacheKey}`);

    await redis.del(cacheKey);

    return destroyed;
  }

  /**
   * Updates DB and saves over cache
   *
   * @param {Object} values
   * @param {Object} options
   *
   * @returns {Sequelize.Model}
   */
  async update(values, options) {
    await super.update(values, options);

    // Reload so sequelize cache will get proper data for things like automatically updated modified_on
    await this.reload();

    const cacheKey = this.constructor.getCacheKey(this.get('id'));
    const value = JSON.stringify(this.get());

    const ttl = this.getCacheTtl();
    log(`> Setting cache for ${cacheKey} for ${ttl} as ${value}`);
    await redis.set(cacheKey, value, 'EX', ttl);

    return this;
  }
}
```

**Comment by DanielHreben** [comment]
> And you're against extending classes I imagine? I know all the arguments for composition over extending :) 
Not really, just trying to use right tool for the job


> The code below shows what I'm currently doing, that I would swap out for your repo. I basically take any model I want to use cache on and have it extend this instead of Sequelize.Model directly.
I'm not deeply dived to the code, but I think It should work good for your specific project, however it's hard to extract general case that could be solved by library. 

> In terms of ticket #29, I'd imagine cache keys can be set by serialising options like where & order together - or allowing folks to define the cache key on certain calls.
That was my original proposal (see ticket history), but we stick with custom keys because if you want to invalidate cached it's easier to pass custom cache key, rather than reconstruct same query and options previously used as cache key. 

> I think things like findAll can automatically be invalidated similarly to what I did below.
If you want to keep all table entries in cache and invalidate it at any write - yes, you can do it automatically, but in this case looks like your caching strategy probably wrong. 
Idea of another cache type described in #29 is to allow users cache any query result (for example `SELECT * FROM goods WHERE isOnSaleNow = true`) and then invalidate it when they know it's time (in this example another sale with different delated goods started). It's impossible to invalidate automatically, because of WHERE part of the query specific to application logic, so this lib gonna only provide an api to abstract caching, and let you build your custom login on top of it.

**Comment by DaveStein** [comment]
👍 is all I can say to that ha. Thanks for responses!
