### ISSUE TITLE
Manually clearing the cache for a model

### ISSUE THREAD

**Issue by JesalR** [DanielHreben/sequelize-transparent-cache#52]
I was wondering if there is a way to clear the cache for a specific model, or with a certain path prefix?
We have models that are queried and cached, but can be updated en-masse, using the class update, increment, decrement, and Sequelize query methods. As such, the values in the cache will need to be cleared on these occurrences. Is there a way to do this through this library, or will I need to go directly to redis and do it manually?

**Comment by DanielHreben** [comment]
Hi!
I think this is a valid use case, not yet supported. You are more than welcome to contribute this functionality ;)

**Comment by DanielHreben** [comment]
Hi! It's not that easy to delete the set of values in most of cache systems, see discussion in here:
https://github.com/DanielHreben/sequelize-transparent-cache/issues/48

If you need to do that, you probably using cache in a wrong way. 
Maybe you could just use short TTL's?

**Comment by JesalR** [comment]
The way I'm currently using it is that I have a model that is 1 to 1 with users, but not primary keyed by the user ID.

The controller that retrieves that model for a user uses a manual cache key based on the User ID.

However certain infrequent operations will edit many instances of that model, and so the cache for all of those will need to be cleared. I suppose it's possible to clear each one individually by finding what user IDs were effected with an extra query and calling Model.cache(userId).clear() for each userId. 

Currently, I go straight to the redis adapter to clear using this function
```
const clearCache = (pattern) => new Promise((resolve, reject) => {
  var stream = redis.scanStream({
    match: pattern
  });

  const clearer = function (keys) {
    try {
      if (keys.length) {
        var pipeline = redis.pipeline();
        keys.forEach(function (key) {
          pipeline.del(key);
        });
        pipeline.exec(function(err, results) {
          resolve();
        });
      } else {
        resolve();
      }
    } catch (e) {
      reject(e);
    }
  };

  const ender = () => {
    stream.off('data', clearer);
    stream.off('end', ender)
  }

  stream.on('data', clearer);
  stream.on('end', ender);
})
```

But seemingly, according to the linked issue, this may not be a good idea
