### ISSUE TITLE
Nested includes only returns one level down from the cache

### ISSUE THREAD

**Issue by iknowmac** [DanielHreben/sequelize-transparent-cache#62]
Currently, I'm using sequelize-transparent-cache, ioredis and redis to run the following...
```javascript
const include = [{
    model: Parent,
    include: [{ model: Child }]
}];
Model.cache(cacheKey).findAll({ include: include });
```
Please excuse the brevity of the above example.
The first query returns the nested object, however, the "hit" from the cache only returns the parent include. Thanks in advance for your help on this ;-)

**Comment by DanielHreben** [comment]
Hi! Sorry, this is a bug, only 1 level of nested include is possible now. I will try my best to fix this asap, but might not happen before next month. 
Dublicate - https://github.com/DanielHreben/sequelize-transparent-cache/issues/61
