### ISSUE TITLE
License info is missing

### ISSUE THREAD

**Issue by puzpuzpuz** [DanielHreben/sequelize-transparent-cache#64]
We're considering add `sequelize-transparent-cache` adaptor for [Hazelcast IMDG](https://hazelcast.org/imdg/), but one thing seems to be weird. The repo seems to be missing license information. Is it on purpose? If not, could you tell me if that's a permissive license and add `LICENSE` file into the repo?

**Comment by puzpuzpuz** [comment]
I've found CC-BY 4.0 specified in `package.json` files within packages. Still, it would be nice to have a `LICENSE` file in the root.

**Comment by DanielHreben** [comment]
Hi! Yeah, it's CC-BY 4.0. Is this license suits your needs? No problem, I will add `LICENSE` file as well.

**Comment by puzpuzpuz** [comment]
CC-BY 4.0 is a permissive license, so users should have no problems with it.

> No problem, I will add `LICENSE` file as well.

Many thanks!
