### ISSUE TITLE
Is there any way to get all cache entries? 

### ISSUE THREAD

**Issue by SiddhantJ19** [DanielHreben/sequelize-transparent-cache#67]

**Comment by DanielHreben** [comment]
I would like to see some more details about what you are actually wanna do.

**Comment by SiddhantJ19** [comment]
I just want to extend on features for some other adapter. Maybe I can do some PRs which you can review. Having a way to view all cache entries might help in the development. What do you say?

**Comment by DanielHreben** [comment]
Cache systems like Redis or Memcached are not optimized for returning lists. 
See: https://redis.io/commands/keys 
This is not a good idea for such calls in this project.

**Comment by DanielHreben** [comment]
Also see discussion in https://github.com/DanielHreben/sequelize-transparent-cache/issues/48

**Comment by SiddhantJ19** [comment]
ioredis provides a stream interface for SCAN. Check [this](https://github.com/luin/ioredis#streamify-scanning)
